<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\..\examples\ImportCommandes.Plugin\Commandes\*.cs" Link="PluginSources\%(Filename)%(Extension)" />
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\HangfireDemo.Core\HangfireDemo.Core.csproj" />
    <ProjectReference Include="..\..\src\HangfireDemo.Api\HangfireDemo.Api.csproj" />
  </ItemGroup>
</Project>
